### PR TITLE
Make sure profiler reads from disk

### LINKED ISSUE #102: profiler gives wrong results because of file caching
The goal of the profiler is to help pick the right combination of threads and parallel nonces to get optimal POST proving speed (going over the data on disk and finding labels) given the user's real disk read speed.

The profiler creates a file on a disk filled with garbage and then goes over it doing its work a few times in a loop. The problem is that the file gets cached in RAM in the first iteration so all subsequent ones read from RAM instead of disk. This defeats the purpose because the benchmark is not limited by disk read speed anymore.

### PR DESCRIPTION
**Pull request by poszu**
Closes #102

What changed:
- the data file is filled with random data instead of zeros,
- file cache is dropped before reading the file on every iteration (each iter reads the whole file from the beginning to the end),
- fixed the default data file location for windows (it used to be /tmp/data.bin).

### CODE REVIEW

File: profiler/src/util/macos.rs [hunk 1]
```diff
@@ -0,0 +1,6 @@
+use std::{error::Error, fs::File, path::Path};
+
+pub(crate) fn open_without_cache(path: &Path) -> Result<File, Box<dyn Error>> {
+    let file = File::open(path)?;
+    Ok(file)
```
Comment (fasmat) [inline profiler/src/util/macos.rs:5]: I assume this should work:

```rust
    let ret = unsafe {
        libc::fcntl(
            file.as_raw_fd(),
            libc::F_NOCACHE,
            1 as libc::c_int,
        )
    };
```

based on: https://stackoverflow.com/a/2307055

**Review by fasmat — APPROVED** [review]

File: profiler/src/util/macos.rs (hunk 1 above)
Comment (poszu) [reply profiler/src/util/macos.rs:5]: Good hint! 

However, according to https://developer.apple.com/forums/thread/25464, `F_NOCACHE` will avoid caching the file, but it doesn't remove it from the cache. I need to think about preventing caching or dropping the file from the cache.
