### PR TITLE
[profiler] create directory for the test file

### LINKED ISSUE #229: Fail to create the profiler data file if directory doesn't exist
## Reproduction steps
Execute profiler with `--data-file` pointing to non-existing directory:
```
profiler --data-file=/tmp/i-dont-exist/profiler.bin
```

## Affected code:
https://github.com/spacemeshos/post-rs/blob/ec396075d07f2c2f39f13bb4ab9a0a4ab275a38b/profiler/src/main.rs#L162-L163

## Expected behavior:
It should create `/tmp/i-dont-exist` directory for the profiler.bin file.

### PR DESCRIPTION
**Pull request by poszu**
Closes #229

### CODE REVIEW

File: profiler/src/main.rs [hunk 1]
```diff
@@ -160,7 +160,15 @@ struct PerfResult {
...
 // Prepare file for benchmarking, possibly appending random data to it if needed.
 fn prepare_data_file(path: &Path, size: u64) -> eyre::Result<()> {
-    let file = OpenOptions::new().write(true).create(true).open(path)?;
+    if let Some(parent) = path.parent() {
+        std::fs::create_dir_all(parent)
+            .wrap_err_with(|| format!("creating directory {}", parent.display()))?;
+    }
+    let file = OpenOptions::new()
+        .write(true)
+        .create(true)
```
Comment (fasmat) [inline profiler/src/main.rs:169]: GH actions complains that `.truncate(true)` should also be added to the options.

**Review by fasmat — APPROVED** [review]
